### ISSUE TITLE
Error while running "python train_ner.py data/products.normalized.trimmed.supplemented.tagged.csv"

### ISSUE THREAD

**Issue by theimgclist** [etano/productner#4]
I am trying to run the code as described. However when I run the code **python train_ner.py data/products.normalized.trimmed.supplemented.tagged.csv**, i got the below error 

D:\Product Classifier>python train_ner.py data/products.normalized.trimmed.supplemented.tagged.csv
Using TensorFlow backend.
Processed 297765 texts.
Getting labels...
Traceback (most recent call last):
  File "train_ner.py", line 49, in <module>
    main(sys.argv)
  File "train_ner.py", line 42, in main
    labels = ner.get_labels(tags)
  File "D:\Product Classifier\ner.py", line 105, in get_labels
    labels.append(to_categorical(np.asarray(indexed_tags), num_classes=4))
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\utils\np_utils.py", line 25, in to_categorical
    categorical[np.arange(n), y] = 1
IndexError: index 4 is out of bounds for axis 1 with size 4

I am not sure if I missed something. This is the first time I have reported an issue. Please let me know if any other details are needed.

**Comment by etano** [comment]
this is fixed.
