### ISSUE TITLE
where is Product\ Dataset.csv?

### ISSUE THREAD

**Issue by yiwuhouzz** [etano/productner#7]
Couldn't find it.

**Comment by etano** [comment]
It get's generated.

**Comment by am05mhz** [comment]
based on the readme file, `Product\ Dataset.csv` should be an input file, and the generated file is `Product\ Dataset.processed.csv`

> Extract information
> To reproduce Product\ Dataset.processed.csv, run the following:
> 
> python extract.py ./models/ Product\ Dataset.csv

so, where is the file?

**Comment by etano** [comment]
This file actually doesn't exist. You'll need to make it or point it at the original data file.
