### ISSUE TITLE
typeerror : 

### ISSUE THREAD

**Issue by suhasdatascience** [etano/productner#9]
python extract.py ./models/ Product\ Dataset.csv

getting error like shown below when trying to execute the above code.

    main(sys.argv)
  File "extract.py", line 75, in main
    writer = csv.DictWriter(outfile, fieldnames=reader.fieldnames+['category', 'brand'])
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by etano** [comment]
Is the first line of Product\ Dataset.csv the header fields?

**Comment by suhasdatascience** [comment]
Hello , earlier there was no header files, now I added it manually, now the issue has been resolved, thanks for the update, but finally i can able to see the category values has been classified, but brand column has no values in it in Product.Dataset.processed.csv file, please find attached for more information.
![issue](https://user-images.githubusercontent.com/32155222/43260845-3c27cf68-90f8-11e8-9466-9ddd9c4c80b1.png)

**Comment by etano** [comment]
For these, the model failed and did not find a brand.

I've uploaded a test Product\ Dataset.csv. See if you can get better performance on it.
